version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name : minio
    ports: 
      - "9001:9001"
      - "9002:9002"
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9002
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qwertyuiop
    volumes:
      - .miniodata:/data
    command: server /data --console-address ":9001"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: gss/logsearch:latest
    container_name: logsearch
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge